---

# option to exclude python extension from build
build_python_extension: no

# enable tasks responsible for building and publishing of lets-plot python package
enable_python_package: no

# enable geom_livemap
enable_livemap: no

# -------------------------------------------------------------------
# Python settings
# -------------------------------------------------------------------
python:
  bin_path: /anaconda3/bin
  include_path: /anaconda3/include/python3.7m


# -------------------------------------------------------------------
# PyPI settings
# -------------------------------------------------------------------
pypi:
  # credentials on test.pypi.org
  test:
    username:
    password:
  # credentials on pypi.org
  prod:
    username:
    password:


# -------------------------------------------------------------------
# Bintray settings
# -------------------------------------------------------------------
bintray:
  user:
  key: