---

# enable tasks responsible for building and publishing of lets-plot python package
enable_python_package: no

# -------------------------------------------------------------------
# Python settings
# -------------------------------------------------------------------
python:
  bin_path: /anaconda3/bin
  include_path: /anaconda3/include/python3.8


# -------------------------------------------------------------------
# PyPI settings
# -------------------------------------------------------------------
pypi:
  # credentials on test.pypi.org
  test:
    username:
    password:
  # credentials on pypi.org
  prod:
    username:
    password:


# -------------------------------------------------------------------
# Sonatype settings
#
# User with deployment permission to Sonatype Nexus repository.
#
# In addition, each publication must be signed using a PGP key.
# Create file "~/.gradle/gradle.properties":
#   signing.keyId=your_keyid_here (short)
#   signing.password=your_password_here
#   signing.secretKeyRingFile=/Users/you/.gnupg/secring.kbx
# -------------------------------------------------------------------
sonatype:
  username:
  password:
